import { Poppins } from "next/font/google";
import "./globals.css";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import { TOAST_DURATION_IN_MS } from "@/constants";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable}`}>
        <MaxWidthWrapper>
          <Navbar />
          {children}
        </MaxWidthWrapper>
        <Toaster
          position='top-right'
          duration={TOAST_DURATION_IN_MS}
        />
      </body>
    </html>
  );
}
